services:
  api:
    networks:
      - backend
      - egress
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    container_name: recipes-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: ${DATABASE_CONNECTION_STRING}
      AppSettings__Secret: ${JWT_SECRET}
      AppSettings__Issuer: Recipes.Api
      AppSettings__Audience: Recipes.Client
      AppSettings__RefreshTokenExpirationDays: 7
      AppSettings__AccessTokenExpirationMinutes: 15
    expose:
      - "8080"

  web:
    networks:
      - frontend
      - backend
    build:
      context: src/Web
      dockerfile: Dockerfile
    container_name: recipes-web
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/nginx/certs:ro
    ports:
      - "${WEB_HTTP_PORT:-80}:80"
      - "${WEB_HTTPS_PORT:-443}:443"

networks:
  frontend:
  backend:
    internal: true
  egress:
